###
POST http://127.0.0.1:3001/api/login HTTP/1.1 
content-type: application/json

{
  "username": "yarijky",
  "password": "yarijky"
}

###
POST http://127.0.0.1:3001/api/login HTTP/1.1 
content-type: application/json

{
  "username": "yorro9",
  "password": "yorro9"
}