### 
POST http://127.0.0.1:3001/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "This is my first blogpost",
  "author": "Yari is my name",
  "url": "I dont't have an url",
  "likes": 90
}

### 
POST http://127.0.0.1:3001/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "This is my second blogpost",
  "author": "Luca is my name",
  "url": "I dont't have an url",
  "likes": 10
}

### 
POST http://127.0.0.1:3001/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "This is my third blogpost",
  "author": "Chri is my name",
  "url": "I dont't have an url",
  "likes": 30
}

### 
POST http://127.0.0.1:3001/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "This is THE ONE to delete",
  "author": "THE ONE is my name",
  "url": "I dont't have an url",
  "likes": 0
}